---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: permission-matrix
  namespace: uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-permission-matrix-uat
  storageClassName: nfs-csi
