---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ms-k8-job-shared
  namespace: prod
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: ms-k8-job-shared-prod
  storageClassName: nfs-csi
