bases:
- ../../base/uat
resources:
- ../base
namespace: uat
configMapGenerator:
- name: level-config
  envs:  
  - config/lvl_config.env
- name: level-sync-config
  envs:  
  - config/lvl_sync_config.env  
generatorOptions:
  disableNameSuffixHash: true