---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: configs-configurations
  namespace: uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-configs-configurations-uat
  storageClassName: nfs-csi
