---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: levels-tree
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-levels-tree-dev
  storageClassName: nfs-csi
