---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: levels-tree
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-levels-tree-prod
  storageClassName: nfs-csi
