bases:
- ../../base/dev
resources:
- ../base
configMapGenerator:
- name: level-config
  envs:  
  - config/lvl_config.env
- name: level-sync-config
  envs:  
  - config/lvl_sync_config.env  
namespace: dev
generatorOptions:
  disableNameSuffixHash: true     

