---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spin-shared
  namespace: uat
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-shared-uat
  storageClassName: nfs-csi
