apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers-dev
  namespace: dev
subjects:
  - kind: Group
    name: developers
    namespace: dev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developers-dev
  apiGroup: rbac.authorization.k8s.io
