apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduler
  namespace: prod
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/status
      - secrets
      - configmaps
      - podtemplates
      - services
      - deployments
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]

