---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sg-event-scripts
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: spin-sg-event-scripts-dev
  storageClassName: nfs-csi
